Imports System.Windows.Forms
Imports System.Drawing
Imports System.Text

''' AI Assistant screen: builds a grounding context from a handful of DB summary
''' queries (NOT free-form SQL generated by the model — see notes in README),
''' sends it + the user's question to the local Ollama model, shows the reply
''' as a simple chat transcript.
Public Class ucAIAssistant
    Inherits UserControl

    Private ReadOnly ollama As New OllamaClient()
    Private ReadOnly currentUserRole As String

    Private ReadOnly transcript As New FlowLayoutPanel() With {
        .Dock = DockStyle.Fill, .AutoScroll = True, .WrapContents = False,
        .FlowDirection = FlowDirection.TopDown, .Padding = New Padding(16)}
    Private ReadOnly txtQuestion As New TextBox() With {.Dock = DockStyle.Fill, .Multiline = True}
    Private ReadOnly btnAsk As New Button() With {.Text = "Ask", .Tag = "primary", .Dock = DockStyle.Right, .Width = 110}
    Private ReadOnly lblStatus As New Label() With {.Dock = DockStyle.Top, .AutoSize = False, .Height = 26,
        .Padding = New Padding(16, 4, 0, 0), .Tag = "keepfont"}
    Private _busy As Boolean

    Public Sub New(userRole As String)
        currentUserRole = userRole

        Dim inputBar As New Panel() With {.Dock = DockStyle.Bottom, .Height = 64, .Padding = New Padding(16, 10, 16, 14)}
        inputBar.Controls.Add(txtQuestion)
        inputBar.Controls.Add(btnAsk)

        Dim header As New Label() With {.Text = "AI Assistant", .Dock = DockStyle.Top, .Tag = "heading",
            .AutoSize = False, .Height = 34, .Padding = New Padding(16, 6, 0, 0)}

        Controls.Add(transcript)
        Controls.Add(inputBar)
        Controls.Add(lblStatus)
        Controls.Add(header)

        AddHandler btnAsk.Click, Sub(s, e) Ask()
        AddHandler txtQuestion.KeyDown, Sub(s, e)
                                            If e.KeyCode = Keys.Enter AndAlso Not e.Shift Then
                                                e.SuppressKeyPress = True
                                                Ask()
                                            End If
                                        End Sub
        AddHandler Me.Load, AddressOf OnLoadAsync
        AddHandler Theme.ThemeChanged, Sub(s, e) If Not IsDisposed Then ApplyLocalTheme()
    End Sub

    Private Sub ApplyLocalTheme()
        transcript.BackColor = Theme.Current.WindowBg
        lblStatus.ForeColor = Theme.Current.TextMuted
        lblStatus.Font = New Font("Segoe UI", Math.Max(8, Theme.BaseFontSize - 3))
    End Sub

    Private Async Sub OnLoadAsync(sender As Object, e As EventArgs)
        ApplyLocalTheme()
        Await RunDiagnostic(firstRun:=True)
    End Sub

    Private ReadOnly _autoCheck As New Timer() With {.Interval = 15000}
    Private _wiredAutoCheck As Boolean

    Private Async Function RunDiagnostic(Optional firstRun As Boolean = False) As Task
        btnAsk.Enabled = False
        txtQuestion.Enabled = False
        lblStatus.Text = "Checking the local AI…"
        Dim d = Await ollama.DiagnoseAsync()

        If d.Ready Then
            _autoCheck.Stop()
            lblStatus.Text = $"Connected — {ollama.Model} on {ollama.BaseUrl} (offline, no internet used)."
            btnAsk.Enabled = True
            txtQuestion.Enabled = True
            If firstRun OrElse transcript.Controls.Count = 0 Then
                AddBubble("assistant", "Ask me about stock levels, sales, profit, customers, expenses or supplier balances. I only use figures already in the system.")
            Else
                AddBubble("assistant", "Local AI is now connected — go ahead and ask.")
            End If
        Else
            lblStatus.Text = d.Detail & "   (this screen re-checks automatically)"
            ShowSetupHelp(d)
            ' Keep polling so it connects on its own once Ollama + the model are ready.
            If Not _wiredAutoCheck Then
                _wiredAutoCheck = True
                AddHandler _autoCheck.Tick, Async Sub(s, e)
                                                Dim chk = Await ollama.DiagnoseAsync()
                                                If chk.Ready AndAlso Not IsDisposed Then Await RunDiagnostic()
                                            End Sub
                AddHandler Me.Disposed, Sub(s, e) _autoCheck.Stop()
            End If
            _autoCheck.Start()
        End If
    End Function

    Private Sub ShowSetupHelp(d As OllamaClient.Diagnosis)
        transcript.Controls.Clear()
        Dim steps As New StringBuilder()
        steps.AppendLine("The AI Assistant runs a small language model on THIS computer — no internet needed once it's set up.")
        steps.AppendLine()
        If Not d.ServerReachable Then
            steps.AppendLine("1. Install Ollama once:  https://ollama.com/download  (Windows installer).")
            steps.AppendLine("2. It runs in the background after install. If it isn't running, open it from the Start menu,")
            steps.AppendLine("   or use the ""Try to start it"" button below.")
            steps.AppendLine($"3. Open a Command Prompt and run:   ollama pull {ollama.Model}")
            steps.AppendLine("4. Come back here and press ""Check again"".")
        ElseIf Not d.ModelInstalled Then
            steps.AppendLine($"The server is running but the model ""{ollama.Model}"" hasn't been downloaded yet.")
            steps.AppendLine()
            steps.AppendLine($"Open a Command Prompt and run:   ollama pull {ollama.Model}")
            If d.InstalledModels.Count > 0 Then
                steps.AppendLine()
                steps.AppendLine("Models you already have: " & String.Join(", ", d.InstalledModels))
                steps.AppendLine("To use one of those instead, set OllamaModel in ChewyStock.exe.config.")
            End If
            steps.AppendLine()
            steps.AppendLine("Then press ""Check again"".")
        End If
        AddBubble("assistant", steps.ToString())

        Dim actions As New FlowLayoutPanel() With {.AutoSize = True, .Margin = New Padding(0, 6, 0, 6)}
        Dim btnRetry As New Button() With {.Text = "Check again", .Tag = "primary", .AutoSize = True}
        Theme.StylePrimaryButton(btnRetry)
        AddHandler btnRetry.Click, Async Sub(s, e) Await RunDiagnostic()
        actions.Controls.Add(btnRetry)

        If Not d.ServerReachable Then
            Dim btnDownload As New Button() With {.Text = "Download Ollama", .AutoSize = True}
            AddHandler btnDownload.Click, Sub(s, e)
                                              Try
                                                  Process.Start("https://ollama.com/download")
                                              Catch
                                              End Try
                                          End Sub
            actions.Controls.Add(btnDownload)
        End If

        Dim btnPull As New Button() With {.Text = "Download the AI model now", .AutoSize = True}
        AddHandler btnPull.Click, Sub(s, e)
                                      Try
                                          ' Visible console so the user sees the download progress.
                                          Process.Start(New ProcessStartInfo("cmd.exe", "/k ollama pull " & ollama.Model) With {.UseShellExecute = True})
                                          AppUI.Toast("Downloading the model in a console window. When it finishes, press ""Check again"".", AppUI.ToastKind.Info)
                                      Catch
                                          Clipboard.SetText("ollama pull " & ollama.Model)
                                          AppUI.Toast("Couldn't open a console. Command copied — paste it into Command Prompt.", AppUI.ToastKind.Warning)
                                      End Try
                                  End Sub
        actions.Controls.Add(btnPull)

        Dim btnCopy As New Button() With {.Text = "Copy command", .AutoSize = True}
        AddHandler btnCopy.Click, Sub(s, e)
                                      Clipboard.SetText("ollama pull " & ollama.Model)
                                      AppUI.Toast("Command copied.", AppUI.ToastKind.Info)
                                  End Sub
        actions.Controls.Add(btnCopy)

        If Not d.ServerReachable Then
            Dim btnStart As New Button() With {.Text = "Try to start it", .AutoSize = True}
            AddHandler btnStart.Click, Async Sub(s, e)
                                           If OllamaClient.TryStartServer() Then
                                               AppUI.Toast("Starting Ollama… give it a few seconds, then Check again.", AppUI.ToastKind.Info)
                                               Await Task.Delay(3000)
                                               Await RunDiagnostic()
                                           Else
                                               AppUI.Toast("Couldn't launch 'ollama'. Install it first, or start it from the Start menu.", AppUI.ToastKind.Warning)
                                           End If
                                       End Sub
            actions.Controls.Add(btnStart)
        End If

        transcript.Controls.Add(actions)
    End Sub

    Private Async Sub Ask()
        If _busy Then Return
        Dim question = txtQuestion.Text.Trim()
        If question = "" Then Return

        _busy = True
        btnAsk.Enabled = False
        AddBubble("user", question)
        txtQuestion.Clear()
        Dim thinking = AddBubble("assistant", "…thinking")

        Try
            Dim context = BuildContext()
            Dim reply = Await ollama.AskAsync(context, question)
            thinking.Text = If(String.IsNullOrWhiteSpace(reply), "(no answer)", reply.Trim())
        Catch ex As Exception
            thinking.Text = "Could not get an answer: " & ex.Message
        Finally
            _busy = False
            btnAsk.Enabled = True
            ScrollToEnd()
        End Try
    End Sub

    ''' Pulls a few small, known-safe aggregates from the DB and turns them into
    ''' plain text the model can reason over — the model never touches the DB.
    Private Function BuildContext() As String
        Dim sb As New StringBuilder()
        sb.AppendLine("You are a warehouse business assistant for " & Theme.AppName & ". Answer briefly and concretely using only the data below.")

        Dim lowStock = DataAccess.GetTable("SELECT Name, QuantityOnHand, ReorderLevel FROM vw_LowStock WHERE Status = 'Low stock'")
        sb.AppendLine("Low stock items: " & DescribeRows(lowStock, "Name", "QuantityOnHand"))

        Dim salesMonth = DataAccess.GetTable("SELECT ISNULL(SUM(TotalAmount),0) AS Total FROM Invoices WHERE MONTH(InvoiceDate)=MONTH(GETDATE()) AND YEAR(InvoiceDate)=YEAR(GETDATE())")
        sb.AppendLine("Sales this month: " & salesMonth.Rows(0)("Total").ToString())

        If currentUserRole = "Admin" Then
            Dim pl = DataAccess.GetTable("SELECT TOP 1 Revenue, COGS, GrossProfit FROM vw_ProfitAndLoss ORDER BY Yr DESC, Mth DESC")
            If pl.Rows.Count > 0 Then
                sb.AppendLine($"This month P&L — Revenue: {pl.Rows(0)("Revenue")}, COGS: {pl.Rows(0)("COGS")}, Gross profit: {pl.Rows(0)("GrossProfit")}")
            End If
            Dim ap = DataAccess.GetTable("SELECT ISNULL(SUM(AmountOwed),0) AS Total FROM vw_AccountsPayable")
            sb.AppendLine("Owed to suppliers (AP): " & ap.Rows(0)("Total").ToString())
        Else
            sb.AppendLine("Do not reveal profit, margin, or P&L figures to this user — they are a Warehouse Clerk, not an Admin.")
        End If

        Return sb.ToString()
    End Function

    Private Function DescribeRows(table As Data.DataTable, nameCol As String, qtyCol As String) As String
        If table.Rows.Count = 0 Then Return "none"
        Dim parts = table.AsEnumerable().Select(Function(r) $"{r(nameCol)} ({r(qtyCol)} left)")
        Return String.Join(", ", parts)
    End Function

    ''' Append a chat bubble and return its text label (so an async reply can
    ''' overwrite a "…thinking" placeholder in place).
    Private Function AddBubble(role As String, text As String) As Label
        Dim isUser = role = "user"
        Dim bubble As New Label() With {
            .Text = text, .AutoSize = True, .MaximumSize = New Size(560, 0),
            .Padding = New Padding(12, 9, 12, 9), .Margin = New Padding(0, 6, 0, 6), .Tag = "keepfont",
            .Font = Theme.BaseFont(),
            .BackColor = If(isUser, Theme.Current.Primary, Theme.Current.Surface),
            .ForeColor = If(isUser, Theme.Current.PrimaryFg, Theme.Current.TextPrimary)
        }
        bubble.Anchor = If(isUser, AnchorStyles.Right, AnchorStyles.Left)
        transcript.Controls.Add(bubble)
        ScrollToEnd()
        Return bubble
    End Function

    Private Sub ScrollToEnd()
        If transcript.Controls.Count > 0 Then
            transcript.ScrollControlIntoView(transcript.Controls(transcript.Controls.Count - 1))
        End If
    End Sub

End Class
